export const PolicyData = [
  {
    name: 'Universal Basic Income',
    url: 'https://www.yang2020.com/policies/the-freedom-dividend/',
    category: '',
    keywords: [
      'ubi',
      'freedom dividend',
      '$1000',
      'money',
      'one thousand dollars',
      'universal basic income',
      'thomas paine',
      'martin luther king',
      'richard nixon',
      'milton friedman'
    ]
  },
  {
    name: 'Medicare for All',
    url: 'https://www.yang2020.com/policies/medicare-for-all/',
    category: '',
    keywords: [
      'medicare for all',
      'healthcare',
      'doctors',
      'health',
      'medicine',
      'medical',
      'holistic',
      'public option',
      'single payer',
      'mental health'
    ]
  },
  {
    name: 'Human-Centered Capitalism',
    url: 'https://www.yang2020.com/policies/human-capitalism/',
    'category': '',
    keywords: [
      'human capitalism',
      'human centered capitalism',
      'income',
      'standard of living',
      'life expectancy',
      'childhood success rates',
      'infant mortality',
      'national well-being',
      'mental health',
      'infrastructure',
      'marriage rates and success',
      'environmental quality',
      'incarceration',
      'journalism',
      'dynamism',
      'mobility',
      'public safety',
      'civic engagement',
      'cybersecurity',
      'economic competitiveness',
      'jobs',
      'work'
    ]
  },
  {
    name: 'Robo-Calling Text Line',
    url: 'https://www.yang2020.com/policies/robo-calling-text-line/',
    category: '',
    keywords: [
      'robocalls',
      'robo-calling',
      'phone',
      'cellphone',
      'solicitor',
      'soliciting',
      'harrassment',
      'FCC',
      'complaint',
      'illegal',
      'crime'
    ],
  },
  {
    name: 'Regulate AI and other Emerging Technologies',
    url: 'https://www.yang2020.com/policies/regulating-ai-emerging-technologies/',
    category: '',
    keywords: [
      'ai',
      'artificial intelligence',
      'technology',
      'regulate',
      'regulation',
      'machine learning',
      'Elon Musk',
      'secretary of technology',
      'silicon valley'
    ],
  },
  {
    name: 'Net Neutrality',
    url: 'https://www.yang2020.com/policies/net-neutrality/',
    category: '',
    keywords: [
      'internet',
      'net',
      'utility',
      'web',
      'ISP',
      'comcast',
      'verizon',
      'at&t',
      't-mobile',
      'sprint'
    ],
  },
  {
    name: 'Making Taxes Fun',
    url: 'https://www.yang2020.com/policies/making-taxes-fun/',
    category: '',
    keywords: [
      'tax',
      'fun',
      'holiday',
      'federal holiday',
      'federal',
      'government',
      'irs',
      'revenue',
      'revenue day'
    ],
  },
  {
    name: 'Media Fragmentation',
    url: 'https://www.yang2020.com/policies/media-fragmentation/',
    category: '',
    keywords: [
      'media responsibility task force',
      'media',
      'press',
      'facts',
      'fact checking',
      'facebook',
      'twitter',
      'social media',
      'russia',
      'russian intervention',
      'foreign intervention',
      'intervention'
    ],
  },
  {
    name: 'Economic Crime',
    url: 'https://www.yang2020.com/policies/economic-crime/',
    category: '',
    keywords: [
      'finance',
      'fraud',
      'wall street',
      'market',
      'free market',
      'abuse',
      'protection',
      'mortgage',
      'financial crisis',
      'recession',
      'illegal'
    ],
  },
  {
    name: 'Modern Time Banking',
    url: 'https://www.yang2020.com/policies/modern-time-banking/',
    category: '',
    keywords: [
      'volunteering',
      'shelter',
      'community',
      'community engagement',
      'tutor',
      'coaching',
      'town fair',
      'social cohesion',
      'human capitalism'
    ],
  },
  {
    name: 'Modernize Voting',
    url: 'https://www.yang2020.com/policies/modernize-voting/',
    category: '',
    keywords: [
      'voting',
      'vote',
      'fairness',
      'security',
      'government',
      'polling',
      'blockchain',
      'effective government',
      'technology',
      'democracy'
    ],
  },
  {
    name: 'Nuclear Energy',
    url: 'https://www.yang2020.com/policies/nuclear-energy/',
    category: '',
    keywords: [
      'energy',
      'nuclear',
      'green new deal',
      'sustainability',
      'environment',
      'carbon',
      'carbon-free',
      'electricity',
      'electric'
    ],
  },
  {
    name: 'Algorithmic Trading/Fraud',
    url: 'https://www.yang2020.com/policies/algorithmic-trading-fraud/',
    category: '',
    keywords: [
      'CFTC',
      'trading',
      'crime',
      'fraud',
      'market',
      'free market',
      'algorithms',
      'equity',
      'accountability',
      'investigation',
      'illegal'
    ],
  },
  {
    name: 'Zoning',
    url: 'https://www.yang2020.com/policies/zoning/',
    category: '',
    keywords: [
      'housing',
      'affordable',
      'zoning laws',
      'local',
      'development',
      'home ownership',
      'housing cost',
      'rent',
      'buy',
      'law'
    ],
  },
  {
    name: 'Entice High-Skill Individuals',
    url: 'https://www.yang2020.com/policies/enticing-high-skill-individuals/',
    category: '',
    keywords: [
      'h1b',
      'f1',
      'H1-B',
      'F-1',
      'visa',
      'immigrant',
      'immigration',
      'jobs',
      'work'
    ],
  },
  {
    name: 'American Mall Act',
    url: 'https://www.yang2020.com/policies/american-mall-act/',
    category: '',
    keywords: [
      'mall',
      'community',
      'community center',
      'socialization',
      'commerce',
      'amazon',
      'investment',
      'economy',
      'local',
      'retail',
      'buildings',
      'blight',
      'jobs',
      'work'
    ],
  },
  {
    name: 'Tort Reform/Reasonableness Dismissals',
    url: 'https://www.yang2020.com/policies/tort-reform-reasonableness-dismissals/',
    category: '',
    keywords: [
      'litigation',
      'tort',
      'lawsuit',
      'justice',
      'court',
      'crime',
      'judge',
      'appeal'
    ],
  },
  {
    name: 'Financial Transaction Tax',
    url: 'https://www.yang2020.com/policies/financial-transaction-tax/',
    category: '',
    keywords: [
      'taxes',
      'tax',
      'finance',
      'bubble',
      'economy',
      'market',
      'stock',
      'trade',
      'fund',
      'mutual fund'
    ],
  },
  {
    name: 'File Income Taxes',
    url: 'https://www.yang2020.com/policies/filing-income-taxes/',
    category: '',
    keywords: [
      'taxes',
      'tax',
      'turbotax',
      'efile',
      'e-file',
      'tax prep',
      'IRS',
      'government',
      'automation',
      'treasury'
    ],
  },
  {
    name: 'Capital Gain/Carried Interest Tax',
    url: 'https://www.yang2020.com/policies/capital-gain-carried-interest-tax/',
    category: '',
    keywords: [
      'tax',
      'taxes',
      'interest',
      'tax code',
      'revenue',
      'carried',
      'interest',
      'loophole',
      'capital',
      'gain'
    ],
  },
  {
    name: 'Ease the Transition to Self-Driving Vehicles',
    url: 'https://www.yang2020.com/policies/trucking-czar/',
    category: '',
    keywords: [
      'cars',
      'technology',
      'self-driving',
      'self driving',
      'vehicles',
      'truck',
      'truck driving',
      'trucker',
      'automation',
      'economy',
      'jobs',
      'work',
      'trucking czar',
      'transition',
      'tax',
      'taxes'
    ],
  },
  {
    name: 'Implement Mandatory Paid Leave Policy',
    url: 'https://www.yang2020.com/policies/mandatory-vacation/',
    category: '',
    keywords: [
      'paid leave',
      'parent',
      'family',
      'families',
      'community',
      'children',
      'child',
      'childcare',
      'mental health',
      'stress',
      'leave',
      'mandatory leave',
      'jobs',
      'work',
      'economy',
      'productivity'
    ],
  },
  {
    name: 'Make it Easy for Americans to Move for Work',
    url: 'https://www.yang2020.com/policies/get-america-moving/',
    category: '',
    keywords: [
      'home',
      'economy',
      'dynamism',
      'jobs',
      'moving',
      'move',
      'work',
      'subsidy',
      'subsidize',
      'cost',
      'mobility',
      'refund',
      'IRS',
      'federal',
      'profession'
    ],
  },
  {
    name: 'Modernize Military Spending',
    url: 'https://www.yang2020.com/policies/rechannel-military-spending/',
    category: '',
    keywords: [
      'military',
      'spending',
      'modern',
      'modernization',
      'soldiers',
      'heath',
      'healthcare',
      'health care',
      'veterans',
      'mental health',
      'cyberterrorism',
      'nuclear material'
    ],
  },
  {
    name: 'Life-Skills Education in All High Schools',
    url: 'https://www.yang2020.com/policies/life-skills-education/',
    category: '',
    keywords: [
      'education',
      'life skills',
      'life-skills',
      'high schools',
      'schools',
      'finance',
      'jobs',
      'interviews',
      'cooking',
      'food',
      'health',
      'mental health',
      'time management',
      'physical fitness'
    ],
  },
  {
    name: 'Make Community College Affordable for All',
    url: 'https://www.yang2020.com/policies/close-skills-gap-community-college/',
    category: '',
    keywords: [
      'college',
      'higher education',
      'university',
      'education',
      'student debt',
      'debt',
      'tuition',
      'schools',
      'community',
      'jobs',
      'work',
      'economy',
      'loans'
    ],
  },
  {
    name: 'Free Financial Counseling for All',
    url: 'https://www.yang2020.com/policies/financial-counseling/',
    category: '',
    keywords: [
      'finance',
      'financial literacy',
      'counseling',
      'banking',
      'retirement',
      'investment',
      'investing',
      'school',
      'high school',
      'education',
      'IRS',
      'online course',
      'AI',
      'advisors',
      'personal finance',
      'college',
      'communtiy college',
      'higher education',
      'advice',
      'savings'
    ],
  },
  {
    name: 'Make it Easier to Save for Retirement',
    url: 'https://www.yang2020.com/policies/telescoping-retirement-accounts/',
    category: '',
    keywords: [
      'finance',
      'retirement',
      'investing',
      'investment',
      'savings',
      'tax-free',
      'retirement accounts',
      'income'
    ],
  },
  {
    name: 'Support the Revival of Earmarks',
    url: 'https://www.yang2020.com/policies/support-revival-earmarks/',
    category: '',
    keywords: [
      'earmarks',
      'legislation',
      'pass legislation',
      'government',
      'federal',
      'house',
      'senate',
      'representatives',
      'senators',
      'revenue',
      'constituents'
    ],
  },
  {
    name: 'Expand Access to Medical Experts',
    url: 'https://www.yang2020.com/policies/expanding-medical-licensure/',
    category: '',
    keywords: [
      'medicine',
      'medical',
      'doctors',
      'physicians',
      'PCP',
      'primary care specialists',
      'IBM',
      'watson',
      'diagnoses',
      'nurse practitioners',
      'heath',
      'healthcare',
      'preventative',
      'maintenance',
      'patients',
      'technology'
    ],
  },
  {
    name: 'Reduce Student Loan Burden',
    url: 'https://www.yang2020.com/policies/student-loan-debt/',
    category: '',
    keywords: [
      'education',
      'college',
      'university',
      'higher education',
      'loans',
      'lenders',
      'lending',
      'schools',
      'student loans',
      'debt',
      'student debt',
      'burden',
      'borrowers',
      'economy',
      'forgiveness',
      'bankruptcy',
      'bankruptcy laws',
      '10×10 Student Loan Emancipation Act'
    ],
  },
  {
    name: 'Rebuild American Infrastructure',
    url: 'https://www.yang2020.com/policies/rebuild-america/',
    category: '',
    keywords: [
      'infrastructure',
      'roads',
      'bridges',
      'airports',
      'invest',
      'investment',
      'modernize',
      'automate',
      'power plants',
      'sewers',
      'water systems',
      'clean water',
      'water treatment',
      'flint',
      'fiber-optic',
      'network',
      'internet',
      'high-speed internet',
      'solar',
      'solar-cell roadways',
      'electric',
      'electricity',
      'technologies',
      'technology',
      'rebuild america',
      'challenge grant',
      'jobs',
      'economy',
      'sustainability'
    ],
  },
  {
    name: 'Fund Autism Intervention',
    url: 'https://www.yang2020.com/policies/autism-intervention-funding/',
    category: '',
    keywords: [
      'medicine',
      'mental health',
      'medical',
      'child',
      'children',
      'health',
      'family',
      'families',
      'healthcare',
      'health care',
      'autism',
      'autistic',
      'autism spectrum',
      'CDC',
      'Department of Education'
    ],
  },
  {
    name: 'Fund Medical Technology Innovation',
    url: 'https://www.yang2020.com/policies/medical-technology-innovation/',
    category: '',
    keywords: [
      'medicine',
      'medical',
      'technology',
      'technologies',
      'vaccines',
      'antiseptics',
      'antibiotics',
      'innovation',
      'investments',
      'AI',
      'automation',
      'tax incentives',
      'rural',
      'preventative care',
      'care'
    ],
  },
  {
    name: 'Increase Assistance for Single Parents',
    url: 'https://www.yang2020.com/policies/single-parent-assistance/',
    category: '',
    keywords: [
      'parenting',
      'parent',
      'children',
      'child',
      'family',
      'families',
      'support',
      'support network',
      'single parents',
      'community',
      'housing',
      'communal housing',
      'single mothers',
      'Big Brothers Big Sisters of America',
      'big brother',
      'big sister'
    ],
  },
  {
    name: 'Improve the American Scorecard',
    url: 'https://www.yang2020.com/policies/measuring-the-economy/',
    category: '',
    keywords: [
      'mental health',
      'scorecard',
      'america',
      'data',
      'health',
      'Quality of life',
      'health-adjusted life expectancy',
      'happiness',
      'well-being',
      'mental health',
      'underemployment',
      'income inequality',
      'consumer debt',
      'student debt',
      'work and civic engagement levels',
      'volunteerism',
      'infant mortality',
      'quality of infrastructure',
      'access to education',
      'marriage and divorce rates',
      'substance abuse and related deaths',
      'national optimism',
      'personal dynamism',
      'economic mobility',
      'GDP',
      'directives'
    ],
  },
  {
    name: 'Prevent Airlines from Removing Customers',
    url: 'https://www.yang2020.com/policies/prevent-airlines-removing-customers/',
    category: '',
    keywords: [
      'airlines',
      'airplanes',
      'travel',
      'customers',
      'FAA',
      'removed',
      'removing',
      'safety',
      'auction',
      'seat',
      'airplane seats'
    ],
  },
  {
    name: 'Prosperity Grants',
    url: 'https://www.yang2020.com/policies/prosperity-grants/',
    category: '',
    keywords: [
      'government',
      'non-profit',
      'donations',
      'donate',
      'tax',
      'philanthropy',
      'local',
      'community',
      'IRS',
      'tax code'
    ],
  },
  {
    name: 'Automatically Sunset Old Laws',
    url: 'https://www.yang2020.com/policies/automatically-sunsetting-old-laws/',
    category: '',
    keywords: [
      'laws',
      'congress',
      'representatives',
      'senators',
      'KPIs',
      'key performance indicators',
      'sunset period'
    ],
  },
  {
    name: 'Free Marriage Counseling for All',
    url: 'https://www.yang2020.com/policies/free-marriage-counseling/',
    category: '',
    keywords: [
      'marriage',
      'community',
      'family',
      'families',
      'parent',
      'children',
      'child',
      'single parents',
      'happy',
      'happiness',
      'relationships',
      'divorce',
      'counseling',
      'family counseling',
      'ACA',
      'affordable care act',
      'tax code'
    ],
  },
  {
    name: 'Closely Monitor Mental Health of White House Staff',
    url: 'https://www.yang2020.com/policies/white-house-psychologist/',
    category: '',
    keywords: [
      'mental health',
      'healthcare',
      'health care',
      'health',
      'government',
      'white house',
      'president',
      'vice president',
      'chief of staff',
      'psychiatrists',
      'psychologists',
      'stress',
      'senior government official',
      'emotional',
      'emotions',
      'executive branch',
      'destigmatize mental health issues',
      'white house psychologist corps'
    ],
  },
  {
    name: 'Prevent Corruption among Federal Regulators',
    url: 'https://www.yang2020.com/policies/pay-president-regulators/',
    category: '',
    keywords: [
      'corruption',
      'crime',
      'regulation',
      'government',
      'speaking fees',
      'salary',
      'presidential salary',
      'cabinet members',
      'heads of regulatory agencies',
      'salary',
      'salaries',
      'Bill Clinton',
      'George Bush'
    ],
  },
  {
    name: 'American Exchange Program',
    url: 'https://www.yang2020.com/policies/american-exchange-program/',
    category: '',
    keywords: [
      'exchange',
      'americans',
      'urban',
      'rural',
      'divide',
      'empathy',
      'community',
      'high school',
      'seniors',
      'school',
      'education',
      'local'
    ],
  },
  {
    name: 'Provide Basic Banking Services through the Post Office',
    url: 'https://www.yang2020.com/policies/post-offices-provide-basic-banking-services/',
    category: '',
    keywords: [
      'finance',
      'post office',
      'banking',
      'bank',
      'savings',
      'basic banking services',
      'basic services',
      'loans',
      'lending'
    ],
  },
  {
    name: 'Local Journalism Fund',
    url: 'https://www.yang2020.com/policies/local-journalism-fund/',
    category: '',
    keywords: [
      'journalism',
      'newspapers',
      'news',
      'writing',
      'local',
      'investment',
      'fact-checking',
      'media',
      'library',
      'libraries',
      'government',
      'FCC'
    ],
  },
  {
    name: 'Limit Bureaucracy in the Federal Workforce',
    url: 'https://www.yang2020.com/policies/downsizing-federal-workforce/',
    category: '',
    keywords: [
      'government',
      'federal',
      'bureaucracy',
      'federal workers',
      'jobs',
      'millenials',
      'inefficiency',
      'inefficiencies',
      'efficiency',
      'congress',
      'hiring'
    ],
  },
  {
    name: 'Nuclear Launch Decisions',
    url: 'https://www.yang2020.com/policies/nuclear-launch/',
    category: '',
    keywords: [
      'nuclear missles',
      'nukes',
      'war',
      'conflict',
      'nuclear attack',
      'attack',
      'security',
      'president',
      'vice president',
      'chief of staff'
    ],
  },
  {
    name: 'NCAA Should Pay Athletes',
    url: 'https://www.yang2020.com/policies/ncaa-pay-athletes/',
    category: '',
    keywords: [
      'NCAA',
      'athletes',
      'college',
      'university',
      'higher education',
      'education',
      'student',
      'sports',
      'basketball',
      'football',
      'college athletes',
      'jobs',
      'economy'
    ],
  },
  {
    name: 'Every Cop Gets a Camera',
    url: 'https://www.yang2020.com/policies/every-cop-gets-camera/',
    category: '',
    keywords: [
      'crime',
      'law',
      'police',
      'cop',
      'camera',
      'body camera',
      'transparency',
      'legal',
      'non-lethal',
      'weapons',
      'demilitarise',
      'technology',
      'handprint guns'
    ],
  },
  {
    name: 'Reduce Harm to Children Caused by Smartphones',
    url: 'https://www.yang2020.com/policies/effects-smartphones-human-development/',
    category: '',
    keywords: [
      'smartphones',
      'children',
      'child',
      'social media',
      'parent',
      'family',
      'families',
      'community',
      'dark patterns'
    ],
  },
  {
    name: 'News and Information Ombudsman',
    url: 'https://www.yang2020.com/policies/news-information-ombudsman/',
    category: '',
    keywords: [
      'news',
      'newspapers',
      'ombudsman',
      'libel',
      'media'
    ],
  },
  {
    name: 'American Journalism Fellows',
    url: 'https://www.yang2020.com/policies/american-journalism-fellows/',
    category: '',
    keywords: [
      'journalism',
      'news',
      'newspapers',
      'media'
    ],
  },
  {
    name: 'Invest in America’s Mental Health',
    url: 'https://www.yang2020.com/policies/mental-health/',
    category: '',
    keywords: [
      'mental health',
      'healthcare',
      'health care',
      'health',
      'medicine',
      'medical',
      'treatment'
    ],
  },
  {
    name: 'Hold Pharmaceutical Companies Accountable',
    url: 'https://www.yang2020.com/policies/holding-pharmaceutical-companies-accountable/',
    category: '',
    keywords: [
      'medicine',
      'medical',
      'crime'
    ],
  },
  {
    name: 'Value-Added Tax',
    url: 'Value-Added Tax',
    category: '',
    keywords: [
      'vat',
      'value added tax',
      'taxes',
      'amazon',
      'facebook',
      'google',
      'economy',
      'market',
      'trade',
      'business',
      'tax code'
    ],
  },
  {
    name: 'Make Puerto Rico a State',
    url: 'https://www.yang2020.com/policies/puerto-rican-statehood/',
    category: '',
    keywords: [
      'statehood',
      'puerto rico',
      'natural disasters'
    ],
  },
  {
    name: 'Legalize Marijuana',
    url: 'https://www.yang2020.com/policies/legalization-of-marijuana/',
    category: '',
    keywords: [
      '420',
      'marijuana',
      'pot',
      'dank',
      'legalization',
      'legal',
      'law',
      'drugs',
      'enforcement',
      'african americans',
      'black'
    ],
  },
  {
    name: 'Early Childhood Education for All',
    url: 'https://www.yang2020.com/policies/early-childhood-education/',
    category: '',
    keywords: [
      'children',
      'education',
      'preschools',
      'pre-schools',
      'schools',
      'early',
      'childhood',
      'child',
      'family',
      'families'
    ],
  },
  {
    name: 'Increase Teacher Salaries',
    url: 'https://www.yang2020.com/policies/teacher-salaries/',
    category: '',
    keywords: [
      'teacher',
      'education',
      'schools',
      'student',
      'universities',
      'higher education',
      'jobs',
      'economy'
    ],
  },
  {
    name: 'Carbon Fee and Dividend',
    url: 'https://www.yang2020.com/policies/carbon-fee-dividend/',
    category: '',
    keywords: [
      'environment',
      'carbon',
      'carbon fee',
      'greenhouse gasses',
      'green new deal',
      'taxes',
      'tax'
    ],
  },
  {
    name: 'Promote Vocational Education',
    url: 'https://www.yang2020.com/policies/promoting-vocational-education/',
    category: '',
    keywords: [
      'vocational education',
      'higher education',
      'education',
      'vocation',
      'schools',
      'jobs',
      'work',
      'economy',
      'trades'
    ],
  },
  {
    name: 'Fight for Equal Pay',
    url: 'https://www.yang2020.com/policies/fight-for-equal-pay/',
    category: '',
    keywords: [
      'jobs',
      'work',
      'pay',
      'equality',
      'fairness',
      'economy',
      'women\'s rights',
      'men',
      'women',
      'black',
      'african american',
      'minority',
      'minorities',
      'native americans',
      'hispanic'
    ],
  },
  {
    name: 'Campaign Finance Reform',
    url: 'https://www.yang2020.com/policies/overturning-citizens-united/',
    category: '',
    keywords: [
      'campaign',
      'finance',
      'election',
      'citizens united'
    ],
  },
  {
    name: 'Right to Privacy/Abortion and Contraception',
    url: 'https://www.yang2020.com/policies/right-privacy-abortion-contraception/',
    category: '',
    keywords: [
      'abortion',
      'birth control',
      'contraception',
      'health',
      'reproductive rights',
      'healthcare',
      'medicine',
      'medical',
      'planned parenthood'
    ],
  },
  {
    name: 'Support the DREAM Act',
    url: 'https://www.yang2020.com/policies/support-the-dream-act/',
    category: '',
    keywords: [
      'dreamers',
      'immigration',
      'illegal immigration',
      'citizenship',
      'citizen',
      'pathyway to citizenship',
      'dream act',
      'reform'
    ],
  },
  {
    name: 'Southern Border Security',
    url: 'https://www.yang2020.com/policies/southern-border-security/',
    category: '',
    keywords: [
      'immigration',
      'immigrant',
      'border security',
      'border',
      'security',
      'illegal immigration',
      'illegals',
      'wall',
      'fencing',
      'drones',
      'alien',
      'illegal alien'
    ],
  },
  {
    name: 'Pathway to Citizenship for Undocumented Immigrants',
    url: 'https://www.yang2020.com/policies/pathway-to-citizenship-2/',
    category: '',
    keywords: [
      'immigration',
      'immigrant',
      'citizenship',
      'undocumented',
      'illegals',
      'illegal immigrant',
      'alien',
      'illegal alien'
    ],
  },
  {
    name: 'Control the Cost of Higher Education',
    url: 'https://www.yang2020.com/policies/controlling-cost-higher-education/',
    category: '',
    keywords: [
      'education',
      'college',
      'university',
      'community college',
      'higher education',
      'student debt',
      'loans',
      'cost',
      'administrative costs'
    ],
  },
  {
    name: 'Support for the Arts',
    url: 'https://www.yang2020.com/policies/support-for-the-arts/',
    category: '',
    keywords: [
      'creativity',
      'art',
      'music',
      'film',
      'media',
      'writing',
      'photography',
      'copyright laws',
      'education',
      'schools',
      'royalties',
      'musicians',
      'licensing',
      'Music Modernization Act'
    ],
  },
  {
    name: 'Paid Family Leave',
    url: 'https://www.yang2020.com/policies/paid-family-leave/',
    category: '',
    keywords: [
      'paid leave',
      'parent',
      'family',
      'families',
      'community',
      'children',
      'child',
      'childcare',
      'newborn',
      'mental health',
      'stress',
      'leave',
      'mandatory leave',
      'jobs',
      'work',
      'economy',
      'productivity'
    ],
  },
  {
    name: 'Gun Safety',
    url: 'https://www.yang2020.com/policies/gun-safety/',
    category: '',
    keywords: [
      'guns',
      '2nd amendment',
      'second amendment',
      '2A',
      'handguns',
      'rifles',
      'shotguns',
      'licensing',
      'license',
      'safety',
      'buyback'
    ],
  },
  {
    name: 'Foreign Policy First Principles',
    url: 'https://www.yang2020.com/policies/foreign-policy-first-principles/',
    category: '',
    keywords: [
      'foreign policy',
      'foreign',
      'conflict',
      'war',
      'foreign conflict',
      'foreign relations',
      'UN',
      'international relations',
      'foreign issues',
      'NATO',
      'AUMF',
      'congress',
      'DoD',
      'Department of Defense',
      'audit',
      'abroad'
    ],
  },
  {
    name: 'LGBTQ Rights',
    url: 'https://www.yang2020.com/policies/lgbtq-rights/',
    category: '',
    keywords: [
      'LGBTQ',
      'lesbian',
      'gay',
      'bisexual',
      'transgender',
      'queer',
      'LGBT',
      'LGBT rights',
      'gender rights',
      'equal rights',
      'equality'
    ],
  },
  {
    name: 'Opioid Crisis',
    url: 'https://www.yang2020.com/policies/opioid-crisis/',
    category: '',
    keywords: [
      'treatment',
      'health',
      'healthcare',
      'medicine',
      'crime',
      'drugs',
      'medical',
      'pills',
      'doctors',
      'fentanyl',
      'heroin',
      'oxycontin',
      'percocet'
    ],
  },
  {
    name: 'Reduce Mass Incarceration',
    url: 'https://www.yang2020.com/policies/reduce-mass-incarceration/',
    category: '',
    keywords: [
      'crime',
      'criminal justice',
      'incarceration',
      'african american',
      'black',
      'federal prisions',
      'private prisons',
      'prison',
      'minorities',
      'treatment'
    ],
  },
  {
    name: 'Combat Climate Change',
    url: 'https://www.yang2020.com/policies/climate-change/',
    category: '',
    keywords: [
      'climate',
      'climate change',
      'green new deal',
      'alternative energy',
      'clean',
      'environment',
      'fossil fuels',
      'solar',
      'wind',
      'engergy',
      'power plants',
      'greenhouse gasses',
      'global warming',
      'electric bills',
      'EPA',
      'environmental protection agency'
    ],
  },
  {
    name: 'Decriminalize Opioids',
    url: 'https://www.yang2020.com/policies/decriminalizeopioids/',
    category: '',
    keywords: [
      'crime',
      'decriminalization',
      'treatment',
      'health',
      'healthcare',
      'medicine',
      'drugs',
      'medical',
      'pills',
      'doctors',
      'fentanyl',
      'heroin',
      'oxycontin',
      'percocet'
    ],
  },
  {
    name: 'Ranked Choice Voting',
    url: 'https://www.yang2020.com/policies/rankedchoice/',
    category: '',
    keywords: [
      'government',
      'voting',
      'vote',
      'elections',
      'fairness',
      'ranked choice',
      'third party'
    ],
  },
  {
    name: 'Democracy Dollars',
    url: 'https://www.yang2020.com/policies/democracydollars/',
    category: '',
    keywords: [
      'campaign finance',
      'government',
      'elections',
      'fairness',
      'reform'
    ],
  },
  {
    name: 'Relocate Federal Agencies',
    url: 'https://www.yang2020.com/policies/relocatefederalagencies/',
    category: '',
    keywords: [
      'government',
      'federal agencies',
      'economy',
      'jobs',
      'decentralize',
      'investment'
    ],
  },
  {
    name: 'Extend Daylight Saving Time All Year',
    url: 'https://www.yang2020.com/policies/extend-daylight-savings-time-all-year/',
    category: '',
    keywords: [
      'daylight savings',
      'time',
      'timezones',
      'eastern',
      'central',
      'mountain',
      'pacific'
    ],
  },
  {
    name: 'Decrease Pre-Trial Cash Bail',
    url: '',
    category: '',
    keywords: [
    ],
  },
  {
    name: 'Lower the Voting Age to 16',
    url: '',
    category: '',
    keywords: [
      'sixteen',
      '16',
      'voting',
      'voting age',
      'vote',
      'government',
      'elections'
    ],
  },
  {
    name: 'Revive the Office of Technology Assessment',
    url: '',
    category: '',
    keywords: [
    ],
  },
  {
    name: '18 Year Term Limit for Supreme Court Justices',
    url: '',
    category: '',
    keywords: [
      'court',
      'supreme court',
      'justice'
    ],
  },
  {
    name: 'Empowering MMA Fighters',
    url: '',
    category: '',
    keywords: [
    ],
  },
  {
    name: 'Make Election Day a Holiday',
    url: '',
    category: '',
    keywords: [
      'holiday',
      'elections',
      'voting',
      'vote'
    ],
  },
  {
    name: 'The Penny Makes No Cents',
    url: '',
    category: '',
    keywords: [
      'penny',
      'change',
      'cents'
    ],
  },
  {
    name: 'Quantum Computing and Encryption Standards',
    url: '',
    category: '',
    keywords: [
    ],
  },
  {
    name: 'Reduce Packaging Waste',
    url: '',
    category: '',
    keywords: [
      'waste',
      'amazon',
      'packaging'
    ],
  },
  {
    name: 'End Partisan Gerrymandering',
    url: '',
    category: '',
    keywords: [
      'elections',
      'voting',
      'voter rights',
      'vote',
      'fairness'
    ],
  },
  {
    name: 'Make Washington, DC, a State',
    url: '',
    category: '',
    keywords: [
      'statehood'
    ],
  },
  {
    name: 'Head of Culture and Ceremony',
    url: '',
    category: '',
    keywords: [
    ],
  },
  {
    name: 'Grid Modernization Race to the Top',
    url: '',
    category: '',
    keywords: [
    ],
  },
  {
    name: 'Automatic Voter Registration',
    url: '',
    category: '',
    keywords: [
      'voting',
      'vote',
      'elections'
    ],
  },
  {
    name: 'Expand Selective Schools',
    url: '',
    category: '',
    keywords: [
      'education',
      'schools'
    ],
  },
  {
    name: 'Proportional Selection of Electors',
    url: '',
    category: '',
    keywords: [
      'electoral college',
      'elections',
      'voting',
      'vote'
    ],
  },
  {
    name: 'Crypto/Digital Asset Regulation and Consumer Protection',
    url: '',
    category: '',
    keywords: [
      'crypto',
      'cryptocurrency',
      'bitcoin',
      'etherium',
      'dogecoin'
    ],
  },
  {
    name: 'Restoration of Voting Rights',
    url: '',
    category: '',
    keywords: [
      'voting',
      'voting rights',
      'vote',
      'elections'
    ],
  },
  {
    name: 'Control the Cost of Prescription Drugs',
    url: '',
    category: '',
    keywords: [
    ],
  },
  {
    name: 'Reduce Wildfires',
    url: '',
    category: '',
    keywords: [
    ],
  },
  {
    name: 'Data as a Property Right',
    url: '',
    category: '',
    keywords: [
    ],
  },
  {
    name: 'Timing of Payments for Small Businesses',
    url: '',
    category: '',
    keywords: [
    ],
  },
  {
    name: 'Preservation of Public Lands and Water',
    url: '',
    category: '',
    keywords: [
    ],
  },
  {
    name: 'End Bidding Wars for Corporate Relocation',
    url: '',
    category: '',
    keywords: [
    ],
  }
]

// TEMPLATE
// {
//   name: '',
//   url: '',
//   category: '',
//   keywords: [
//   ],
// },